version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    environment:
      - TZ=America/Edmonton
    ports:
      - 1880:1880
    volumes:
      - node-red-data:/data
      - ./flows.json:/external/flows.json
      - ./flows_cred.json:/external/flows_cred.json

  pp:
    build: .
    image: firefly-iii-pp:latest
    container_name: firefly-iii-pp
    ports:
      - 9091:80
    volumes:
      - ./thunder-tests:/thunder
      - ./keyValueStore.json:/keyValueStore/store.json

volumes:
  node-red-data: